package PlatformGameShared.Enums;

public enum SpriteType {
    PLAYER,
    PLAYERINVULN,
    PLATFORM,
    UNSOLIDPLATFORM,
    WEAPONPICKUP,
    PROJECTILEBULLET,
    PROJECTILESWORD,
    PROJECTILEBOMB,
    PROJECTILEBOMBEXPLODE,
    PROJECTILEROCKET,
    AXE,
    NONE
}
