/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.Gamelevel;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-10T09:24:57.661Z")

@Api(value = "level", description = "the level API")
public interface LevelApi {

    @ApiOperation(value = "Find Game level by name", nickname = "getLevelByName", notes = "", response = Gamelevel.class, tags={ "serverapp","users", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Gamelevel.class),
        @ApiResponse(code = 400, message = "Invalid name supplied"),
        @ApiResponse(code = 404, message = "Level not found") })
    @RequestMapping(value = "/level/{levelname}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Gamelevel> getLevelByName(@ApiParam(value = "Name of the level that needs to be retrieved",required=true) @PathVariable("levelname") String levelname);


    @ApiOperation(value = "gets all levels", nickname = "getMaps", notes = "Retrieves all level names", response = String.class, responseContainer = "List", tags={ "users","serverapp", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "list of levels", response = String.class, responseContainer = "List") })
    @RequestMapping(value = "/level",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<String>> getMaps();

}
