/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.PlayerLoginData;
import io.swagger.model.PlayerLoginResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-10T09:24:57.661Z")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "logs a player in", nickname = "loginPlayer", notes = "Retrieves player log in data if username and password don't match", response = PlayerLoginResponse.class, tags={ "serverapp", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "player logged in", response = PlayerLoginResponse.class),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 403, message = "login data has not match") })
    @RequestMapping(value = "/login",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PlayerLoginResponse> loginPlayer(@ApiParam(value = "Login data to check"  )  @Valid @RequestBody PlayerLoginData playerLogin);

}
