/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-10T09:24:57.661Z")

@Api(value = "stats", description = "the stats API")
public interface StatsApi {

    @ApiOperation(value = "retrieves player stats", nickname = "getPlayerInfo", notes = "By passing in the appropriate options, you can search for available inventory in the system ", response = Integer.class, tags={ "users", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "player wins matching criteria", response = Integer.class),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/stats",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Integer> getPlayerInfo(@NotNull @ApiParam(value = "The Player name for which to return information about", required = true) @Valid @RequestParam(value = "playerName", required = true) String playerName);

}
