name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  include:
    - stage: test
      env: TEST_SUITE=none
      install: skip # bundle install is not required
      script: "mvn test"